<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PROFESSIONAL CMS THEMEING</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../assets/css/qcmst-template.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../../../dist/js/html5shiv.js"></script>
    <script src="../../../dist/js/respond.min.js"></script>
    <![endif]-->
</head>





<body>

<div class="container">

    <div class="row">
        <div class="col-xs-4" id="process-graphic">
            <div class="row">
                <div class="col-xs-4" id="process-graphic-font-left">
                    Send Us Your Design.
                </div>
                <div class="col-xs-4" id="process-graphic-font-center">
                    We'll Create Your Vision.
                </div>
                <div class="col-xs-4" id="process-graphic-font-right">
                    Recieve in 5-7 days!
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12" >
            <form role="form" method="post" action="/get-started/estimate">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Your email address">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control" rows="3" name="description" id="description"></textarea>
                    <p class="help-block">Tell us about the style of your site! We will reach out to you within 24 hours for more details and to collect the PSD file.</p>
                </div>

                <button type="submit" class="btn btn-primary">Let's do this!</button>
            </form>
        </div>
    </div>



    <div class="row">
        <div class="col-xs-12" id="footer-font">
            <h1>**Coming Soon.  Stay Tuned.  For questions about launch date please send us an email at quickcmsthemes@gmail.com**</h1>
        </div>
        <div class="col-xs-12">
            <h1>*Special launch price. Until the end of the year we will be taking $200 off of the starting price.</h1>
        </div>
    </div>



</div><!-- /.container -->



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../assets/js/jquery.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/analytics.js"></script>
</body>
</html>