<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PROFESSIONAL CMS THEMEING</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../assets/css/qcmst-template.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../../../dist/js/html5shiv.js"></script>
    <script src="../../../dist/js/respond.min.js"></script>
    <![endif]-->
</head>





<body>

<div class="container">

    <div class="row">
        <div class="col-xs-4" id="logo-graphic"></div>
        <div class="col-xs-4" id="button">
            <div class="row">
                <div class="col-xs-4" id="button-font">
                    GET STARTED!
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-4" id="process-graphic">
            <div class="row">
                <div class="col-xs-4" id="process-graphic-font-left">
                    Send Us Your Design.
                </div>
                <div class="col-xs-4" id="process-graphic-font-center">
                    We'll Create Your Vision.
                </div>
                <div class="col-xs-4" id="process-graphic-font-right">
                    Recieve in 5-7 days!
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6" id="panel-graphic-left">
            <div class="row">
                <div class="col-xs-6" id="panel-font-center">
                    Supported CMS's?
                    <ul>
                        <li>Wordpress</li>
                        <li>Drupal</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-xs-6" id="panel-graphic-right">
            <div class="row">
                <div class="col-xs-6" id="panel-font-center">
                    What do you get?
                    <ul>
                        <li>Your CMS expertly themed</li>
                        <li>Cross browser support</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6" id="panel-graphic-left-2">
            <div class="row">
                <div class="col-xs-6" id="panel-left-2-font-center">
                    <ul>
                        <li>And more. We are always looking to expand our offerings so please reach out to us.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-6" id="panel-graphic-right-2">
            <div class="row">
                <div class="col-xs-6" id="panel-right-2-font-center">
                    <ul>
                        <li>Mobile ready theme</li>
                        <li>Friendly and prompt service</li>
                        <li>100% guaranteed satisfaction</li>
                        <li>An absolute bargain!</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12" id="footer-font">
            <h1>**Coming Soon.  Stay Tuned.  For questions about launch date please send us an email at quickcmsthemes@gmail.com**</h1>
        </div>
        <div class="col-xs-12">
            <h1>*Special launch price. Until the end of the year we will be taking $200 off of the starting price.</h1>
        </div>
    </div>



</div><!-- /.container -->



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../assets/js/jquery.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/analytics.js"></script>
</body>
</html>