<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PROFESSIONAL CMS THEMEING</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../assets/css/qcmst-template.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../../../dist/js/html5shiv.js"></script>
    <script src="../../../dist/js/respond.min.js"></script>
    <![endif]-->
</head>





<body>

<div class="container">

    <div class="row">
        <div class="col-xs-12" >
           <h1 id="thank-you">Thank you!</h1>
            <br />
            <p id="thank-you-pg">
                We will be reaching out to you in the next 24 hours to introduce ourselves and collect the design for your vision!
            </p>
        </div>
    </div>

</div><!-- /.container -->



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../assets/js/jquery.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/analytics.js"></script>
</body>
</html>